const Questions = [
  [
    "Q1: In Greek mythology, who was the hunter who was torn apart by Artemis' dog?",
    "Pluto",
    "Homer",
    "Actaeon",
    "Buster",
  ],
  [
    "Q2: Amazon removed/blocked how many products for claiming to treat or cure COVID-19 or for price-gouging?",
    "500,000",
    "80",
    ">>1 Million",
    "It's a business",
  ],
  [
    "Q3: Which company had not converted some production capacity to hand sanitizer?",
    "Miller Brewing Co.",
    "Woodford Reserve",
    "Moonshine Ridge Inc.",
    "Seven Stills Brewery & Distillery",
  ],
  [
    "Q4: Who is the current Supreme Leader of North Korea?",
    "Kim Jong-chul",
    "Kim Jong-un",
    "Kim Jong-il",
    "Kim Jong-nam",
  ],
  [
    "Q5: Who did the San Francisco 49ers draft in 2020?",
    "Javon Kinlaw",
    "Bryan Edwards",
    "Jordan Love",
    "Henry Ruggs III",
  ],
  [
    "Q6: Which NBA player halted the '19-'20 Season?",
    "Kevin Durant",
    "Donavan Mitchell",
    "Draymond Green",
    "Rudy Gobert",
  ],
  [
    "Q7: Which Bio-Pharm firm gave hopes to treat COVID-19?",
    "Biogen Inc.",
    "Gilead Sciences, Inc.",
    "Moderna, Inc.",
    "Regeneron PhX, Inc.",
  ],
  [
    "Q8: Which Sector crashed the week of 4/20/20?",
    "Energy",
    "Materials",
    "Financials",
    "Consumer discretionary",
  ],
];
const Answers = [
  "Actaeon",
  ">>1 Million",
  "Miller Brewing Co.",
  "Kim Jong-un",
  "Javon Kinlaw",
  "Rudy Gobert",
  "Gilead Sciences, Inc.",
  "Energy",
];
